export const data = [
    {
        propertyName: "Sunset Villa",
        address: "123 Ocean View Drive, Malibu, CA",
        numberOfRooms: 5,
        facilities: ["Swimming Pool", "Gym", "Private Beach Access", "Wi-Fi"],
    },
    {
        propertyName: "Mountain Retreat",
        address: "456 Alpine Road, Aspen, CO",
        numberOfRooms: 4,
        facilities: ["Fireplace", "Hot Tub", "Ski Access", "Wi-Fi"],
    },
    {
        propertyName: "City Lights Apartment",
        address: "789 Downtown Ave, New York, NY",
        numberOfRooms: 2,
        facilities: ["Rooftop Terrace", "Gym", "Parking", "Wi-Fi"],
    },
    {
        propertyName: "Lakeside Cottage",
        address: "101 Lakeview Lane, Tahoe, NV",
        numberOfRooms: 3,
        facilities: ["Boat Dock", "Firepit", "Wi-Fi", "Private Garden"],
    },
    {
        propertyName: "Desert Oasis",
        address: "202 Desert Road, Phoenix, AZ",
        numberOfRooms: 6,
        facilities: ["Pool", "Outdoor Kitchen", "Wi-Fi", "Home Theater"],
    },
    {
        propertyName: "Urban Loft",
        address: "987 Uptown Street, Chicago, IL",
        numberOfRooms: 2,
        facilities: ["Gym", "Parking", "Wi-Fi", "Concierge"],
    },
    {
        propertyName: "Seaside Escape",
        address: "345 Beachfront Blvd, Miami, FL",
        numberOfRooms: 5,
        facilities: ["Private Beach", "Pool", "Wi-Fi", "Spa"],
    },
    {
        propertyName: "Forest Haven",
        address: "777 Green Tree Rd, Portland, OR",
        numberOfRooms: 4,
        facilities: ["Hiking Trails", "Fireplace", "Wi-Fi", "Private Garden"],
    },
    {
        propertyName: "Downtown Condo",
        address: "654 Central Ave, Los Angeles, CA",
        numberOfRooms: 3,
        facilities: ["Rooftop Pool", "Gym", "Wi-Fi", "Parking"],
    },
    {
        propertyName: "Hilltop Mansion",
        address: "456 Skyline Drive, San Francisco, CA",
        numberOfRooms: 7,
        facilities: ["Private Gym", "Wine Cellar", "Wi-Fi", "Home Theater"],
    },
    {
        propertyName: "Cozy Bungalow",
        address: "101 Palm Tree Blvd, Tampa, FL",
        numberOfRooms: 3,
        facilities: ["Garden", "Wi-Fi", "Parking", "BBQ Area"],
    },
    {
        propertyName: "Luxury Penthouse",
        address: "333 Highrise St, Dallas, TX",
        numberOfRooms: 4,
        facilities: ["Rooftop Pool", "Gym", "Wi-Fi", "Concierge"],
    },
    {
        propertyName: "Country Cottage",
        address: "567 Country Lane, Nashville, TN",
        numberOfRooms: 3,
        facilities: ["Fireplace", "Private Garden", "Wi-Fi", "Parking"],
    },
    {
        propertyName: "Modern Duplex",
        address: "890 Contemporary Dr, Austin, TX",
        numberOfRooms: 4,
        facilities: ["Gym", "Wi-Fi", "Smart Home Integration", "Parking"],
    },
    {
        propertyName: "Beachfront Villa",
        address: "432 Sand Dune St, Malibu, CA",
        numberOfRooms: 6,
        facilities: ["Private Beach", "Pool", "Wi-Fi", "Spa"],
    },
    {
        propertyName: "Riverside Cabin",
        address: "222 River Bend Rd, Bend, OR",
        numberOfRooms: 4,
        facilities: ["Fireplace", "Wi-Fi", "Private Dock", "BBQ Area"],
    },
    {
        propertyName: "Urban Studio",
        address: "145 City Center, New York, NY",
        numberOfRooms: 1,
        facilities: ["Gym", "Wi-Fi", "Concierge", "Parking"],
    },
    {
        propertyName: "Luxury Chalet",
        address: "321 Snowfall St, Park City, UT",
        numberOfRooms: 5,
        facilities: ["Ski-In/Ski-Out", "Hot Tub", "Wi-Fi", "Fireplace"],
    },
    {
        propertyName: "Suburban Home",
        address: "909 Quiet St, Orlando, FL",
        numberOfRooms: 4,
        facilities: ["Garden", "Wi-Fi", "Parking", "Playground"],
    },
    {
        propertyName: "City Loft",
        address: "567 Downtown Ave, Denver, CO",
        numberOfRooms: 2,
        facilities: ["Gym", "Wi-Fi", "Concierge", "Parking"],
    },
    {
        propertyName: "Penthouse Suite",
        address: "333 Skyline Tower, San Francisco, CA",
        numberOfRooms: 3,
        facilities: ["Private Terrace", "Gym", "Wi-Fi", "Concierge"],
    },
    {
        propertyName: "Greenfield Estate",
        address: "888 Countryside Rd, Madison, WI",
        numberOfRooms: 6,
        facilities: ["Private Pool", "Tennis Court", "Wi-Fi", "Garden"],
    },
    {
        propertyName: "Cliffside Retreat",
        address: "765 Ocean Cliffs, La Jolla, CA",
        numberOfRooms: 5,
        facilities: ["Private Beach", "Infinity Pool", "Wi-Fi", "Home Theater"],
    },
    {
        propertyName: "Modern Townhouse",
        address: "234 City Lane, Boston, MA",
        numberOfRooms: 3,
        facilities: ["Gym", "Wi-Fi", "Smart Home", "Parking"],
    },
    {
        propertyName: "Lakeview Villa",
        address: "456 Lakefront Drive, Orlando, FL",
        numberOfRooms: 5,
        facilities: ["Boat Dock", "Pool", "Wi-Fi", "BBQ Area"],
    },
    {
        propertyName: "Skylight Loft",
        address: "444 Uptown Blvd, Seattle, WA",
        numberOfRooms: 2,
        facilities: ["Rooftop Terrace", "Gym", "Wi-Fi", "Concierge"],
    },
    {
        propertyName: "Charming Cottage",
        address: "987 Meadow Way, Burlington, VT",
        numberOfRooms: 3,
        facilities: ["Fireplace", "Private Garden", "Wi-Fi", "Parking"],
    },
    {
        propertyName: "Luxury Mansion",
        address: "123 Hilltop Lane, Beverly Hills, CA",
        numberOfRooms: 8,
        facilities: ["Private Gym", "Spa", "Wi-Fi", "Home Theater"],
    },
    {
        propertyName: "Rustic Lodge",
        address: "321 Wooded Path, Jackson, WY",
        numberOfRooms: 6,
        facilities: ["Fireplace", "Hot Tub", "Wi-Fi", "Hiking Trails"],
    },
    {
        propertyName: "Midtown Apartment",
        address: "555 Central Ave, Atlanta, GA",
        numberOfRooms: 2,
        facilities: ["Gym", "Wi-Fi", "Parking", "Concierge"],
    },
    {
        propertyName: "Countryside Manor",
        address: "789 Rolling Hills Rd, Dallas, TX",
        numberOfRooms: 7,
        facilities: ["Pool", "Tennis Court", "Wi-Fi", "Private Garden"],
    },
    {
        propertyName: "Skyscraper Condo",
        address: "987 Skyline Blvd, Chicago, IL",
        numberOfRooms: 3,
        facilities: ["Rooftop Pool", "Gym", "Wi-Fi", "Concierge"],
    },
    {
        propertyName: "Beach House",
        address: "678 Shoreline Dr, Santa Monica, CA",
        numberOfRooms: 5,
        facilities: ["Private Beach", "Pool", "Wi-Fi", "BBQ Area"],
    },
    {
        propertyName: "Urban Penthouse",
        address: "234 Highrise Ave, Houston, TX",
        numberOfRooms: 4,
        facilities: ["Gym", "Rooftop Pool", "Wi-Fi", "Concierge"],
    },
    {
        propertyName: "Lake Cabin",
        address: "345 Lakeside Rd, Boulder, CO",
        numberOfRooms: 4,
        facilities: ["Firepit", "Private Dock", "Wi-Fi", "Hiking Trails"],
    },
    {
        propertyName: "Seaside Bungalow",
        address: "890 Coastline St, Laguna Beach, CA",
        numberOfRooms: 3,
        facilities: ["Private Beach", "Wi-Fi", "BBQ Area", "Parking"],
    },
    {
        propertyName: "Modern Estate",
        address: "101 Contemporary Lane, Phoenix, AZ",
        numberOfRooms: 6,
        facilities: ["Smart Home", "Pool", "Wi-Fi", "Outdoor Kitchen"],
    },
    {
        propertyName: "Chic Condo",
        address: "444 Downtown Blvd, Miami, FL",
        numberOfRooms: 2,
        facilities: ["Gym", "Wi-Fi", "Concierge", "Parking"],
    },
    {
        propertyName: "Mountain Chalet",
        address: "789 Alpine St, Aspen, CO",
        numberOfRooms: 5,
        facilities: ["Ski-In/Ski-Out", "Hot Tub", "Wi-Fi", "Fireplace"],
    },
];
